/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;

import connector.jdbc;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dhanushree
 */
public class BULDOZER extends javax.swing.JFrame {

    /**
     * Creates new form BULDOZER
     */
    public BULDOZER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label2 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        label8 = new java.awt.Label();
        textField7 = new java.awt.TextField();
        label9 = new java.awt.Label();
        textField8 = new java.awt.TextField();
        label10 = new java.awt.Label();
        textField9 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/mockup-global-distribution.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 730, 530));

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("BOOKING");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, 50));

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(204, 204, 204));
        label3.setText("BOOKING PLACE");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 160, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(204, 204, 204));
        label2.setText("BOOKING DATE [ YYYY-MM-DD ]");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 240, -1));

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(204, 204, 204));
        label4.setText("EMAIL");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 60, -1));

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(204, 204, 204));
        label6.setText("DESTINATION");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, -1, -1));

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(204, 204, 204));
        label7.setText("RETURN DATE");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 120, -1));

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 220, -1));

        textField2.setBackground(new java.awt.Color(0, 51, 51));
        textField2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                textField2ComponentShown(evt);
            }
        });
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1278, 10, 0, -1));
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 220, -1));

        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });
        jPanel1.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 220, -1));
        jPanel1.add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 220, 20));

        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setLabel("BOOK");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 90, 30));

        button2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button2.setLabel("BACK");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 90, 30));

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(0, 51, 51));
        label8.setText("BOOK_ID");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 60, -1, -1));

        textField7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                textField7ComponentShown(evt);
            }
        });
        textField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField7ActionPerformed(evt);
            }
        });
        jPanel1.add(textField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 220, -1));

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(204, 204, 204));
        label9.setText("EX_ID");
        jPanel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 60, -1));

        textField8.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.add(textField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 100, 0, -1));

        label10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 51, 51));
        label10.setText("PRICE");
        jPanel1.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 170, 100, -1));

        textField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField9ActionPerformed(evt);
            }
        });
        jPanel1.add(textField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
VEHICLES VH=new VEHICLES();
       VH.setVisible(true);
       dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
//PAYMENT P=new PAYMENT();
//       P.setVisible(true);
//       dispose(); 
       // TODO add your handling code here:
       String s1=textField1.getText();
            String s2=textField2.getText(); //price
            String s3=textField3.getText();
            String s9=textField9.getText();
            String s5=textField5.getText();
            String s6=textField6.getText(); //ex_id
            String s7 = textField7.getText();
            String s8 = textField8.getText(); // book_id
            // TODO add your handling code here:
           
             try{
          java.sql.Connection con=jdbc.getCon();
          java.sql.Statement st= con.createStatement();
          ResultSet ex_id  = st.executeQuery("select price from excavator where ex_id='"+s6+"'");
          ex_id.next();
          
         // java.sql.Statement st2= con.createStatement();
         // ResultSet excavator_available = st2.executeQuery("select available from excavator where ex_id='"+s6+"'");
        //  excavator_available.next();
        //  if("yes".equals(excavator_available.getString("available").toLowerCase())){
                 
          String SQL_INSERT = "insert into BOOKING (BOOK_PLACE,BOOK_DATE,PRICE,DESTINATION,RETURN_DATE,EX_ID,EMAIL)  values('"+s7+"','"+s1+"','"+ex_id.getInt("price")+"','"+s3+"','"+s5+"','"+s6+"','"+s9+"')";
          java.sql.PreparedStatement statement = con.prepareStatement(SQL_INSERT, java.sql.Statement.RETURN_GENERATED_KEYS);
          int res = statement.executeUpdate();
          if (res > 0){
               ResultSet gen_keys = statement.getGeneratedKeys();
               gen_keys.next();
               JOptionPane.showMessageDialog(null, "success");
               //String no = "NO";
               
//               String SQL_INSERT1 = ;
//               SQL_INSERT1
             //   java.sql.PreparedStatement statement1 = con.prepareStatement("insert into excavator (available) values(?) "+"where ex_id="+ s6);
              //  statement1.setString(1, "NO");
//                statement1.setString(2,
             //  statement1.executeUpdate();
               JOptionPane.showMessageDialog(null, "success");
               PAYMENT P=new PAYMENT(gen_keys.getInt(1), ex_id.getInt("price"));
               P.setVisible(true);
               dispose(); 
          }
            //  jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_ON);
           
      // }else{
        //      JOptionPane.showMessageDialog(null, "Excavator not available!!");
        //  }
             }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_button1ActionPerformed

    private void textField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField7ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    private void textField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField9ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
   // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField7ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_textField7ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_textField7ComponentShown

    private void textField2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_textField2ComponentShown
    
    }//GEN-LAST:event_textField2ComponentShown
                   
                   // TODO add your handling code here:
    //}  
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BULDOZER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BULDOZER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BULDOZER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BULDOZER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BULDOZER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
