/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;

import com.mysql.cj.xdevapi.Statement;
import connector.jdbc;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanushree
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        label4 = new java.awt.Label();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("   LOGIN");
        panel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));

        label2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label2.setText("EMAIL");
        panel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, -1));

        label3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label3.setText("PASSWORD");
        panel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, -1));
        panel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 90, -1));
        panel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 90, -1));

        label4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(51, 153, 255));
        label4.setText("Don't have an account?");
        panel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 180, -1));

        button4.setBackground(new java.awt.Color(0, 0, 0));
        button4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button4.setForeground(new java.awt.Color(255, 51, 0));
        button4.setLabel("LOGIN");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        button5.setBackground(new java.awt.Color(0, 0, 0));
        button5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button5.setForeground(new java.awt.Color(0, 153, 204));
        button5.setLabel("SIGNUP");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        panel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 30));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 230, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/R.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1500, 590));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("                                                    EXCAVATOR HIRE MANAGEMENT SYSTEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 710, 30));

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        button1.setLabel("ABOUT");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 40));

        button2.setBackground(new java.awt.Color(255, 255, 255));
        button2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        button2.setLabel("SERVICE");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, 40));

        button3.setBackground(new java.awt.Color(255, 255, 255));
        button3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        button3.setLabel("CONTACT");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, -1, 40));

        setSize(new java.awt.Dimension(1517, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
       SERVICE S=new SERVICE();
       S.setVisible(true);
       dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       ABOUTUS A=new ABOUTUS();
       A.setVisible(true);
       dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
       USERREGISTRATION U=new USERREGISTRATION();
       U.setVisible(true);
       dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
 CONTACT C=new CONTACT();
       C.setVisible(true);
       dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
            //String s4=String.valueOf(jPasswordField1.getPassword());
           // String s1= textField1.getText();
            
            
           
            // TODO add your handling code here:
           
             try{
          java.sql.Connection con=jdbc.getCon();
          java.sql.Statement st=con.createStatement();
          //java.sql.Statement st
          
          String s4=String.valueOf(jPasswordField1.getPassword());
            String s1= textField1.getText();
            
            //Statement st = (Statement) con.createStatement();
           String sql =("select email, password from USER where email='"+s1+"' and password='"+s4+"'"); 
         //st.executeQuery("select email, password from USER where email='"+s1+"' and password='"+s4+"'");
                 java.sql.ResultSet rs;
                 rs = st.executeQuery(sql);
         if(rs.next()){
             JOptionPane.showMessageDialog(null,"sucessfull");
              VEHICLES VH=new VEHICLES();
        VH.setVisible(true);
       dispose();
         }else{
             JOptionPane.showMessageDialog(this,"unsucessfull");
             textField1.setText("");
             jPasswordField1.setText("");
         }
         // JOptionPane.showMessageDialog(null,"sucessfull");
          con.close();
          
              
            //  jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_ON);
           //VEHICLES VH=new VEHICLES();
        //VH.setVisible(true);
       //dispose();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
                   // TODO add your handling code here:
    }                                       
//    }VEHICLES VH=new VEHICLES();
//       VH.setVisible(true);
//       dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Panel panel1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
