/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;

import connector.jdbc;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanushree
 */
public class PAYMENT extends javax.swing.JFrame {
    private int book_id;
    private int price;
    /**
     * Creates new form PAYMENT
     */
    public PAYMENT(int id, int amount) {
        initComponents();
        book_id = id;
        price = amount;
        
    }

    private PAYMENT() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label5 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        label6 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        label7 = new java.awt.Label();
        textField6 = new java.awt.TextField();
        button3 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        label4 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 204, 0));
        label1.setText("CARD NUMBER");
        panel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, 20));

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        panel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 0, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 204, 0));
        label2.setText("EXP_DATE");
        panel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        panel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 20));

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 204, 0));
        label3.setText("CVV");
        panel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 40, -1));

        textField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField3ActionPerformed(evt);
            }
        });
        panel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, -1));

        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setLabel("PAY NOW");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 30));

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 0, 0));
        label5.setText("BOOK_ID");
        panel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));
        panel1.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 0, 20));

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 0, 0));
        label6.setText("PAYMENT_ID");
        panel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));
        panel1.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setForeground(new java.awt.Color(0, 0, 0));
        label7.setText("PRICE");
        panel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 80, -1));
        panel1.add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 0, -1));

        button3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button3.setLabel("BACK");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 80, 30));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 200, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/DmvdD_eV4AEsGvx.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 510));

        label4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("ENTER PAYMENT INFORMATION");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 390, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
            String s1=textField1.getText();
            String s2=textField2.getText();
            String s5=textField5.getText();
            String s3=textField3.getText();
            String s6=textField6.getText();
            String s4=textField4.getText(); // book_id
            
            // TODO add your handling code here:
           
             try{
          java.sql.Connection con=jdbc.getCon();
          java.sql.Statement st= con.createStatement();
         st.executeUpdate("insert into PAYMENT(CARD_NO,EXP_DATE,CVV,PRICE,BOOK_ID) values('"+s2+"','"+s5+"','"+s3+"','"+price+"','"+book_id+"')");
         
          JOptionPane.showMessageDialog(null,"sucessfull");
          PAYSUCCESS PS=new PAYSUCCESS();
          PS.setVisible(true);
          dispose(); 
          
          // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed
 catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
      }
    }
    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField3ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
BULDOZER B=new BULDOZER();
       B.setVisible(true);
       dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAYMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAYMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAYMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAYMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAYMENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Panel panel1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
