/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproject;

import connector.jdbc;
import javax.swing.JOptionPane;
import java.util.regex.*;
/**
 *
 * @author Dhanushree
 */
public class USERREGISTRATION extends javax.swing.JFrame {
    public String gender;
    /**
     * Creates new form USERREGISTRATION
     */
    public USERREGISTRATION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label4 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        label7 = new java.awt.Label();
        textField6 = new java.awt.TextField();
        label8 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 204, 204));
        label1.setText("REGISTER HERE");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 180, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(204, 204, 204));
        label2.setText("FIRST NAME");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(204, 204, 204));
        label3.setText("LAST NAME");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 110, -1));
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, -1));

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setForeground(new java.awt.Color(204, 204, 204));
        label4.setText("EMAIL");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 60, -1));
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 190, -1));

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setForeground(new java.awt.Color(204, 204, 204));
        label5.setText("YOUR LICENSE NUMBER");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 160, -1));

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setForeground(new java.awt.Color(204, 204, 204));
        label6.setText("PHONE NUMBER");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 140, -1));
        jPanel1.add(textField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 190, -1));

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setForeground(new java.awt.Color(204, 204, 204));
        label7.setText("PASSWORD");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 110, 20));
        jPanel1.add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 190, -1));

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setForeground(new java.awt.Color(204, 204, 204));
        label8.setText("GENDER");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 60, 30));

        button1.setBackground(new java.awt.Color(0, 0, 0));
        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 51, 0));
        button1.setLabel("REGISTER");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, -1));

        button2.setBackground(new java.awt.Color(0, 0, 0));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 51, 0));
        button2.setLabel("BACK");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 100, 30));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setText("FEMALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setText("MALE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/ABCD.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
            String s1=textField1.getText();
            String s2=textField2.getText();
            String s3=textField3.getText();
            String s4=String.valueOf(jPasswordField1.getPassword());
            String s5=textField5.getText();
            String s6=textField6.getText();
            
           
            // TODO add your handling code here:
           
             try{
          java.sql.Connection con=jdbc.getCon();
          java.sql.Statement st= con.createStatement();
          if(!"".equals(s1) && !"".equals(s2) && !"".equals(s3) && !"".equals(s4) && !"".equals(s5) && !"".equals(s6)){
              //phone number check
              Pattern p = Pattern.compile("[0-9]+");
              Matcher m = p.matcher(s5);
              if(m.matches() && s5.length() == 10){
                  
              
         st.executeUpdate("insert into USER values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+gender+"', '"+s5+"','"+s6+"')");
         
          JOptionPane.showMessageDialog(null,"sucessfull");
          VEHICLES VH=new VEHICLES();
             
          VH.setVisible(true);
             dispose();
              }else{
                  JOptionPane.showMessageDialog(null,"phone number contains invalid characters!!");
              }
          }else{
              JOptionPane.showMessageDialog(null,"please fill all the fields");
          }
            //  jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_ON);
           
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
             
           
             //VH.setVisible(true);
             //dispose();
                   // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed
    }
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        HOME H=new HOME();
       H.setVisible(true);
       dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, evt.getActionCommand());
        gender = evt.getActionCommand();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        gender = evt.getActionCommand();
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USERREGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USERREGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USERREGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USERREGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USERREGISTRATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
